spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /deployments/config
      volumes:
        - configMap:
            name: freelancer-service
          name: config       